Improve missing API group/kind message
e.g. if trying to import a Deployment that was last configured
using extensions/v1beta1, the error message improves from:

> Error: Cannot import non-existent remote object
>
> While attempting to import an existing object to "kustomization_resource.p1[\"apps/Deployment/test-ns/test-deploy\"]",
> the provider detected that no object exists with the given id. Only pre-existing objects can be
> imported; check that the id is correct and that it is associated with the provider's configured
>  region or endpoint, or use "terraform apply" to create a new remote object for this resource.

to:

> Error: github.com/kbst/terraform-provider-kustomize/kustomize.kustomizationResourceExists: Can't find Deployment in API group extensions